spring.application.name=TouristGuideAPI
spring.web.error.include-message=always
spring.web.error.include-stacktrace=always

spring.datasource.url=jdbc:mysql://localhost:3306/touristguide
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}